name: Postman Collection Workflow

on:
  push:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron: 30 02 * * *
    - cron: 00 14 * * *
    - cron: 00 06 * * 1-5

jobs:
  run-postman-tests:
    runs-on: ubuntu-latest #ec2-runner

    steps:
      - name: Checkout the code
        uses: actions/checkout@v7.0.1

      - name: Install Nodejs and npm
        uses: actions/setup-node@v6.5.0
        with:
          node-version: '18'

      - name: Install Newman and Html-extra globally
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra

      - name: Run the Postman Collection with newman
        id: newman
        continue-on-error: true
        run: |
          newman run 'Inwarranty-flow Collection.postman_collection.json' \
          -e QA.postman_environment.json \
          -d testData.csv \
          -r cli,htmlextra \
          --reporter-htmlextra-export ./newman/index.html

      - name: Newman Report
        if: always()
        uses: actions/upload-artifact@v7.0.1
        with:
          name: Newman Report
          path: newman/*.html

      - name: Fail workflow if Newman tests failed
        if: ${{ steps.newman.outcome == 'failure' }}
        run: |
          echo "Newman tests failed. Please check the Newman HTML report."
          exit 1

      - name: Creating github page branch
        if: always()
        uses: peaceiris/actions-gh-pages@v4.1.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: newman/

      - name: Send email Notification
        if: always()
        uses: dawidd6/action-send-mail@v22
        with: 
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: Pheonix Inwarranty Flow Test Execution
          to: nikhilt1206@gmail.com
          from: ${{ secrets.EMAIL_USERNAME }}
          body: | 
                Hi,
                Please find the attached HTML Report generated after running the Postman tests via
                Github Actions.
                URL: https://nikhilt1206.github.io/Phoenix-Inwarranty-Flow-Automation/

                Regards,
                Github Actions

      
     
